version: '3'

service:
  server:
    build: ./service
    links: 
      - db
    ports:
      - 8080:8080
    environment:
      DB_HOST: db:3306
      DB_PASSWORD: root

client:
  build: ./client
  links: 
    - service
  ports:
    - 8000:8000